{{- if and .Values.externalSecret.enabled .Values.acme.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "webhook.fullname" . }}-certbot-init
  labels: {{ include "webhook.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "webhook.fullname" . }}-data

      containers:
        - name: certbot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/bash
            - /app/scripts/register-acme.sh
          args:
            - "$(ACME_EAB_KID)"
            - "$(ACME_EAB_HMAC_KEY)"
            - "$(ACME_EMAIL)"
          env:
            - name: ACME_EAB_KID
              valueFrom:
                secretKeyRef:
                  name: {{ include "webhook.fullname" . }}
                  key: acme_eab_kid
            - name: ACME_EAB_HMAC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "webhook.fullname" . }}
                  key: acme_eab_hmac_key
            - name: ACME_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "webhook.fullname" . }}
                  key: acme_email
          volumeMounts:
            - name: data
              mountPath: /data/acme-git-webhook
{{- end }}
