{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "webhook.fullname" . }}
  labels: {{ include "webhook.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ include "webhook.fullname" . }}
    deletionPolicy: Delete
  data:
    - secretKey: api_key
      remoteRef:
        key: {{ .Values.externalSecret.vault.path }}
        property: api_key
    - secretKey: deploy_key
      remoteRef:
        key: {{ .Values.externalSecret.vault.path }}
        property: deploy_key
    - secretKey: vault_secret_id
      remoteRef:
        key: {{ .Values.externalSecret.vault.path }}
        property: vault_secret_id
    - secretKey: f5_password
      remoteRef:
        key: {{ .Values.externalSecret.vault.path }}
        property: f5_password
    - secretKey: acme_eab_kid
      remoteRef:
        key: {{ .Values.externalSecret.vault.path }}
        property: acme_eab_kid
    - secretKey: acme_eab_hmac_key
      remoteRef:
        key: {{ .Values.externalSecret.vault.path }}
        property: acme_eab_hmac_key
    - secretKey: acme_email
      remoteRef:
        key: {{ .Values.externalSecret.vault.path }}
        property: acme_email
{{- end }}
